config/routes.rb
Shortenit::Application.routes.draw do
  root 'urls#new'

  resources :urls, only: [:new, :create, :show]

  resources :redirects, only: [:show], path: ''

  get '/shorten/create' => 'bookmarklets#create'
end

app/models/url.rb
class Url < ActiveRecord::Base
  before_create :generate_unique_token

  validates :original_url, presence: true, url: true

  def self.top_five
    order("hit_count DESC").limit(5)
  end

  def to_param
    token
  end

  def add_hit
    update(hit_count: hit_count + 1)
  end

  private

  def generate_unique_token
    self.token = SecureRandom.hex(2)
    while Url.exists?(token: token)
      self.token = SecureRandom.hex(2)
    end
  end
end

app/models/url_formatter.rb
class UrlFormatter
  def initialize(url)
    @url = URI.escape(url.gsub(" ", ""))
  end

  def formatted_url
    if missing_protocol?
      url.prepend("http://")
    else
      url
    end
  end

  private

  attr_reader :url

  def missing_protocol?
    (missing_http? && missing_https?) && missing_ftp?
  end

  def missing_http?
    !url.starts_with?("http://")
  end

  def missing_https?
    !url.starts_with?("https://")
  end

  def missing_ftp?
    !url.starts_with?("ftp://")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def url_count
    Url.all.count
  end
  helper_method :url_count
end

app/controllers/bookmarklets_controller.rb
class BookmarkletsController < ApplicationController
  def create
    url = Url.find_or_create_by(url_params)
    redirect_to url
  end

  private

  def url_params
    params.require(:url).permit().merge(
      original_url: format(params[:url][:original_url])
    )
  end

  def format(url)
    UrlFormatter.new(url).formatted_url
  end
end

app/controllers/redirects_controller.rb
class RedirectsController < ApplicationController
  def show
    url = find_url
    url.add_hit
    redirect_to url.original_url
  end

  private

  def find_url
    Url.find_by(token: params[:id])
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  respond_to :html

  def new
    @url = Url.new
    @urls = Url.all
  end

  def create
    @url = Url.find_or_create_by(url_params)
    respond_with @url
  end

  def show
    @url = find_url
  end

  private

  def find_url
    Url.find_by(token: params[:id])
  end

  def url_params
    params.require(:url).permit().merge(
      original_url: format(params[:url][:original_url])
    )
  end

  def format(url)
    UrlFormatter.new(url).formatted_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_count
    Url.all.count
  end
end

app/views/application/_errors.html.erb
<% if target.errors.any? %>
  <div class="overlay" id="overlay" style="display:none;"></div>
  <div class="box" id="box">
    <a class="boxclose" id="boxclose"></a>
    <h1>ERRORS</h1>
    <div id='error-list'>
      <% target.errors.full_messages.each do |message| %>
        <div class='error-item'><%= message %></div>
      <% end %>
    </div>
  </div>
  <script>
  $(document).ready(function() {
    $('#overlay').fadeIn(200,function(){
      $('#box').animate({'top':'150px'},300);
    });

    $('#boxclose').click(function(){
      $('#box').animate({'top':'-200px'},500,function(){
        $('#overlay').fadeOut('fast');
      });
    });
  });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>jk.pe shortener</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/1.3.5/ZeroClipboard.js" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-18540444-8', 'jpk.io');
    ga('send', 'pageview');

  </script>
</head>
<body>
  <div id='wrapper'>
    <div id='site-title'>
      <%= link_to 'jk.pe', root_path %>
    </div>
    <div id='site-subtitle'>
      a simple url shortener.
    </div>
    <%= yield %>
    <div id='bookmarklet'>
      Drag this link to your bookmarks bar for a quick way to create short URLs:
      <a href=
        "javascript:location.href='http://jk.pe/shorten/create?url[original_url]='
        +encodeURIComponent(location.href)
        +'&title='+encodeURIComponent(document.title)">
        shortener
      </a>
    </div>
  </div>
  <div id='about-bar'>
    This tool was created by <a href='http://justinkenyon.com'>Justin Kenyon</a>
    with Ruby on Rails, jQuery, and SASS. The code is open source and
    available on <a href='http://github.com/kenyonj/shortenit/'>GitHub</a>.
    This tool has shortened <%= number_with_delimiter(url_count) %> URLs.
  </div>
</body>
</html>

app/views/urls/new.html.erb
<%= render "errors", target: @url %>

<div id="new-form-wrapper">
  <div id="new-url-form">
    <%= form_for @url do |form| %>
      <div class="form-item">
        <%= form.text_field :original_url,
          size: 70,
          placeholder: "Please enter your long url." %>
      </div>
      <div class="button-panel">
        <%= form.submit "shorten", class: "button" %>
      </div>
      <div>
        <table class="table-minimal">
          <thead>
            <tr>
              <th>Long URL</th>
              <th>Short Token</th>
              <th>Hits</th>
            </tr>
          </thead>
          <tbody>
            <% @urls.top_five.each do |url| %>
              <tr>
                <td><%= url.original_url %></td>
                <td><%= link_to url.token, url_path(url.token) %></td>
                <td><%= url.hit_count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/urls/show.html.erb
<div id='show-url-page'>
  <div id='original-url'>
    Original: <span class='url'><%= @url.original_url %></span>
  </div>
  <div id='short-url'>
    Shortened:
    <a class='url' href='<%= redirect_url(@url.token) %>'>
      <%= redirect_url(@url.token) %>
    </a>
    <a href='#' data-clipboard-text='<%= redirect_url(@url.token) %>' id='clip-button'>
      <%= image_tag('copy.png') %>
    </a>
  </div>
</div>
<script>
  $(document).ready(function() {
    ZeroClipboard.config({
      moviePath: "//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/1.3.5/ZeroClipboard.swf",
      trustedDomains: ['*'],
      allowScriptAccess: "always"
    });
    var client = new ZeroClipboard($('#clip-button'));
    client.on('load', function(client) {
      client.on('complete', function(client, args) {
        this.innerHTML = '<%= image_tag('thumb_up.png') %>';
        this.blur();
        $('#clip-button').contents().unwrap();
      });
    });
  });
</script>